# Groups - Permission group for tcf.{group} (ex: tcf.default)
# Commands - List of registered commands that will show in tab complete [MUST NOT HAVE "/" IN CONFIG]
# Note - The user will also need the perm for the command itself
Groups:
    default:
        Commands:
            - help
            - msg
            - r
            - tell
            - tpa
            - tpaaccept
            - back
            - rules
            - afk
            - baltop
            - mail
            - stats
            - shop
            - /calculate
    mod:
        Commands:
            - ban
            - kick
            - mute
config:
    use-as-blacklist: true
